plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sathipay.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sathipay.app'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
    }
}
